# Parameters for TacTip Contact detection on the DigiTac
# ========================================================
# - Tactip camera description
# ========================================================
tactip:
    camera:                             # TacTip camera intrinsic parameter
        fx: 3.2337923992049144e+02      # - x focal lenght
        fy: 3.4230028878526491e+02      # - y focal lenght
        cx: 3.1042034270984652e+02      # - x camera center
        cy: 2.4710324279132291e+02      # - y camera center
        distortion_coeff: [             # - distortion
            2.6255349323300113e-02, 
            -5.2058533856701528e-03,
            -2.5659488140401731e-03, 
            -8.9320087280166040e-04,
            -1.4789370573431722e-02]
    markers: 87                         # Number of markes

    mm2pxl: 15                          # conversion millimeters to pixel in a frame



# ========================================================
# - Image processing parameters
# ========================================================
image_processing:     
    shape:                          # Reshaped image dimension
        width: 640
        height: 480

    mask: polygon                   # Image mask  
    
    blur_kernel_size: 5             # Image noise filtering (Gaussian) kernel size  
    
    circle_recog:                   # Hough Gradient Circle recogition params
        min_radius: 7               #   - min circle radius
        max_radius: 12              #   - min circle radius
        param1: 250                 #   - Upper threshold for the internal Canny edge detecto
        param2: 8                   #   - Threshold for center detection
        min_distance: 27            #   - min distance of adjacent circle




# ========================================================
# - Gaussian Kernel Density Estimation algorithm parameters
# ========================================================
markers_density:            # Params for Gaussian Kernel Algorithm
    rate: 50                # rate [Hz]  

    gaussian_kernel:        # Density Estimator Gaussian Kernel 
        h: 30               #   - Density Estimator Gaussian Kernel std. dev, (TacTip: 15, DigiTac: 30)  
                            #     (it should be close to mean distance in pixels between adjacent markers)                                    
        verbose: False      #   - Print kernel estimation elapsed time 
    
    resolution: 1           # Resolution of pixels for Density estimation
                            # i.e. d(u,v) = density[u//resolution,v//resolution]
                            
    threshold: 0.01         # Maximum density variation allowed in a pixel before contact detection [1/mm^2]
    
    fit:                    # Fit parameters for deformation estimate
        type: "power"   
        a: 0.8776 
        b: 0.6165 




# ========================================================
# - Voronoi cell algorithm parameters
# ========================================================
markers_volume:         # Params for Voronoi Algorithm 
    rate: 30                        # rate [Hz]  
    
    voronoi:                        # Volume voronoi cell     
        vertices: [[144, 456],      #   - List of points to delimit area with markers 
                    [476, 456],     #    (they must be in clockwise or counterclockwise order) 
                    [605, 365],
                    [615,117],
                    [495, 4],
                    [161, 1],
                    [44, 108],
                    [34, 348]]                  
        verbose: True               #   - Print area evaluation elapsed time 

    resolution: 1                   # Resolution of pixels for Density estimation 
                                    # i.e. d(u,v) = density[u//resolution,v//resolution]
    
    threshold: 50                   # Maximum volume variation allowed in a pixel before contact detection [1/mm^2]
    
    fit:                            # Fit parameters for deformation estimate
        type: "logarithmic"
        a: 0.5241 
        b: 22.6688